recipe: default.v1
assistant_id: 20240403-165359-large-chest
language: ru

pipeline:
  - name: WhitespaceTokenizer
    intent_tokenization_flag: true
    intent_split_symbol: "+"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
    max_history: 3
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 8
    epochs: 200


